# This workflow may use actions that are not certified by GitHub.
# They may be provided by a third-party and be governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Code scanning

on:
  # Run on pushes
  push:
    # Remove the line to run when pushing to main
    branches-ignore: ["main"]
  # on PRs
  pull_request:
    branches: ["main"]
  # or on button click
  workflow_dispatch:

jobs:
  analyze:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:

      # Checkout a repository under $GITHUB_WORKSPACE, so the workflow can access it.
      # https://github.com/marketplace/actions/checkout
      - 
        name: Checkout repository
        uses: actions/checkout@v3.4.0
        with:
          # Repository name with owner. For example, actions/checkout.
          # Default: ${{ github.repository }}
          repository: '${{ github.repository }}'
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: 'main'

      # Initialize the CodeQL tools for scanning.
      # https://github.com/github/codeql-action
      - 
        name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - 
        name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      #   If the Autobuild fails above, remove it and uncomment the following three lines. 
      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

      # - 
      #   run: |
      #   echo "Run, Build Application using script"
      #   ./location_of_script_within_repo/buildscript.sh

      - 
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
